# Generated by Django 3.2.6 on 2024-05-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sale_order',
            name='quantity',
        ),
    ]
