# Generated by Django 3.2.6 on 2024-05-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20240512_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasing_invoice',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchasing_invoice',
            name='quantity',
        ),
    ]
