# Generated by Django 3.2.6 on 2024-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_order',
            name='quantity',
            field=models.IntegerField(default=0.0014822134387351778),
            preserve_default=False,
        ),
    ]
