# Generated by Django 3.2.6 on 2024-05-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_sale_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_order',
            name='quantity',
        ),
    ]
