# Generated by Django 3.2.6 on 2024-05-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_sale_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='my_app.product')),
                ('purchasing_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='my_app.purchasing_invoice')),
            ],
        ),
    ]
