# Generated by Django 5.1.6 on 2025-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_customer_supplier_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_type',
            field=models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_name',
            field=models.CharField(max_length=100),
        ),
    ]
