# Generated by Django 5.1.6 on 2025-09-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_productattribute_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.employee'),
        ),
    ]
