# Generated by Django 5.1.6 on 2025-09-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_productattribute_attribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value_date',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value_number',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value_text',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=10),
        ),
    ]
