# Generated by Django 5.1.6 on 2025-09-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_productattribute_attribute_value_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_item',
            name='purchasing_invoice',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchases', to='my_app.employee')),
                ('products', models.ManyToManyField(related_name='Purchases', to='my_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchase_item',
            name='Purchase_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='my_app.purchase'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Purchasing_invoice',
        ),
    ]
