# Generated by Django 5.1.6 on 2025-09-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_purchase_item_purchasing_invoice_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_item',
            old_name='Purchase_id',
            new_name='purchase_id',
        ),
    ]
