# Generated by Django 5.1.6 on 2025-09-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_purchase_id_purchase_item_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
