# Generated by Django 5.1.6 on 2025-09-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_remove_employee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
    ]
