# Generated by Django 5.1.6 on 2025-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_product_expiry_date_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10),
        ),
    ]
