# Generated by Django 5.1.6 on 2025-09-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_purchase_item_total_price_sale_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
