# Generated by Django 5.1.6 on 2025-10-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_salereturn_salereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_item',
            name='original_purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.purchase_item'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.sale_item'),
        ),
    ]
