# Generated by Django 5.1.6 on 2025-10-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_return_item_original_purchase_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_item',
            name='original_purchase_item',
        ),
        migrations.RemoveField(
            model_name='salereturnitem',
            name='original_item',
        ),
    ]
