# Generated by Django 5.1.6 on 2025-10-07 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_remove_return_item_original_purchase_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_item',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.purchase_item'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.sale_item'),
        ),
    ]
