# Generated by Django 5.1.6 on 2025-10-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_alter_product_isbn_returnpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnPurchase',
        ),
    ]
