# Generated by Django 5.1.6 on 2025-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_delete_returnpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='return',
            name='invoice_pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='sale_order',
            name='invoice_pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10),
        ),
    ]
