# Generated by Django 5.1.6 on 2025-10-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_purchase_invoice_pay_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(default=123456798, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
