# Generated by Django 5.1.6 on 2025-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_alter_product_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='invoice_pay_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10),
        ),
    ]
