# Generated by Django 5.1.6 on 2025-11-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_salereturn_invoice_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='my_app.supplier'),
        ),
    ]
