# Generated by Django 5.1.6 on 2025-11-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='my_app.customer'),
        ),
    ]
