# Generated by Django 5.1.6 on 2025-12-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
