# Generated by Django 5.1.6 on 2026-01-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_currency_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_using_as_base', to='my_app.currency'),
        ),
    ]
