# Generated by Django 5.1.6 on 2026-01-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_companyprofile_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='my_app.currency'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exchange_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase_item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='my_app.currency'),
        ),
        migrations.AddField(
            model_name='purchase_item',
            name='exchange_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase_item',
            name='total_price_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
