# Generated by Django 5.1.6 on 2026-01-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_remove_currency_created_at_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='currency',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='currency',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='exchangerate',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='exchangerate',
        #     name='updated_at',
        # ),
        migrations.AddField(
            model_name='sale_item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='my_app.currency'),
        ),
        migrations.AddField(
            model_name='sale_item',
            name='exchange_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale_item',
            name='total_price_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale_order',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='my_app.currency'),
        ),
        migrations.AddField(
            model_name='sale_order',
            name='exchange_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale_order',
            name='total_amount_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
