# Generated by Django 5.1.6 on 2026-01-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0046_remove_currency_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='updated_at',
        ),
    ]
