# Generated by Django 5.1.6 on 2026-01-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0047_remove_currency_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
