# Generated by Django 5.1.6 on 2026-01-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
