# Generated by Django 5.1.6 on 2026-01-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0050_remove_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Out_Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10)),
                ('invoice_pay_method', models.CharField(choices=[('cash', 'Cash'), ('debts', 'Debts')], default='cash', max_length=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Stock_Out_Vouchers', to='my_app.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Out_Vouchers', to='my_app.employee')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Out_Vouchers', to='my_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Out_Voucher_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('total_price_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Stock_Out_Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Out_Voucher_items', to='my_app.stock_out_voucher')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Stock_Out_Voucher_items', to='my_app.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Out_Voucher_items', to='my_app.product')),
            ],
        ),
    ]
