# Generated by Django 5.1.6 on 2026-02-08 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0051_stock_out_voucher_stock_out_voucher_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_out_voucher',
            name='supplier',
        ),
        migrations.AddField(
            model_name='stock_out_voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_Out_Vouchers', to='my_app.customer'),
        ),
    ]
